AWSTemplateFormatVersion: '2010-09-09'
Description: 'DIO Lab - Static Website on S3 (CloudFormation)'

Parameters:
  BucketName:
    Type: String
    Description: dio-gabi-website-2025
    AllowedPattern: '^[a-z0-9.-]{3,63}$'

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Description: Nome do bucket criado
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL do site estático (HTTP)